#!/bin/bash
mkdir bin
chmod +x *
export MAIN_DIR=$PWD
echo "which server do you want to install?"
echo "type [1] java server"
echo "type [2] bedrock server"

choiceForServer=1
read choiceForServer

# Installing Java 16 JDK and playit

#wget -q "https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz" -O bin/java.tar.xz
wget -q "https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz" -O bin/java.tar.xz
cd $MAIN_DIR/bin
echo "> extracting java jdk 16 to the bin/ folder. [THIS MAY TAKE SOME TIME] replace it if you want to use older version of java."
tar -xf java.tar.xz && mv "jdk-17.0.1" java_bins

cd $MAIN_DIR
# If choice is 0 or null then run this command
if [[ -z $choiceForServer ]]; then

  echo "> invaild respond. please try again."
  ./install

# If choice is 1 then run this command
elif [[ $choiceForServer == 1 ]]; then
	
	echo "> running java installation..."
  ./installJava

# If choice is 1 then run this command
elif [[ $choiceForServer == 2 ]]; then
	
	echo "> running bedrock installation..."
  ./installBedrock

else
	echo "> invaild respond. please try again."
	./install
fi
echo "> installing afk (away from keyboard) script "
python3 -m pip install bpytop
echo ""

