#!/bin/bash
export MAIN_DIR=$PWD
echo "> starting the server up. please wait..."                                                                                 
echo "> installing dependencies..."

sudo apt install -y -qq screen wget  

echo "> dependencies installed."

echo "> checking server type..."
if [ -f $MAIN_DIR/server/bedrock_server ]; then

echo "> bedrock server detected! starting server up..."

elif [ ! -f $MAIN_DIR/server/eula.txt ]; then

cd $MAIN_DIR/server
echo "> EULA doesn't exist. creating one."
sudo wget https://cdn.discordapp.com/attachments/715123369200189460/846712565530624050/eula.txt
echo "> EULA completed, restarting server."
cd $MAIN_DIR
screen -S server -d -m ./startJavaServer
clear
echo "> your server just doing a second restart to fix the EULA file."
killall screen
./startserver
exit
elif [ -f $MAIN_DIR/server/eula.txt ]; then
echo "> EULA detected. starting server up..."

else
echo "> your server isn't setup properly. force uninstall..."
cd $MAIN_DIR
./uninstall
echo "> confirmed uninstallation! restarting installation..."
./install
fi

# apparently ppl keep spamming startserver and end up having multiple screens of the same app
killall screen

screen -S server -d -m ./startJavaServer # Starting Java Server
screen -S server -d -m ./startBedrockServer # Starting Bedrock Server
screen -S afk -d -m ./startAfk #Starting AFK app aka bpytop.
screen -S playit -d -m ./startPlayIt # Starting Playit

cd $MAIN_DIR/server
screen -S server -d -m ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi # Starting PocketmineMP
screen -S server -d -m java --add-opens java.base/java.nio=io.netty.common --add-exports java.base/jdk.internal.misc=io.netty.common -p modules -m gomint.server/io.gomint.server.Bootstrap # Starting GoMint
cd $MAIN_DIR

echo "-- cousinz is now online. --"
echo
echo "type [screen -ls] to check the running processes"
echo "type [screen -r server] to enter the Server Console"
echo "type [screen -r playit] to view your server IP"
echo "type [screen -r afk] to not stop your server after 20 minutes"
echo ""
echo "> To stop your server, type './stopserver' to stop"

echo -e '\nchecking if server has launched properly'
./.checkserver 2> crash.log
