#!/bin/bash
clear
echo "> cousinz cerminated!"
echo ""
echo "to run again, type './startserver' to reboot your server."
echo "to delete your server, type './uninstall' to uninstall and delete your server."

# Kill all Screen
killall screen
